export const maritalStatusData = [
  'Married (and not separated)',
  'Widowed (including living common law)',
  'Separated (including living common law)',
  'Divorced (including living common law)',
  'Single (including living common law)',
];

export const cityData = [
  'Karachi',
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Multan',
  'Gujranwala',
  'Hyderabad',
  'Peshawar',
  'Islamabad',
  'Quetta',
  'Sargodha',
  'Sialkot',
  'Bahawalpur',
  'Sukkur',
  'Kandhkot',
  'Sheikhupura',
  'Mardan',
  'Gujrat',
  'Larkana',
  'Kasur',
  'Rahim Yar Khan',
  'Sahiwal',
  'Okara',
  'Wah Cantonment',
  'Dera Ghazi Khan',
  'Mingora',
  'Mirpur Khas',
  'Chiniot',
  'Nawabshah',
  'Kamoke',
  'Burewala',
  'Jhelum',
  'Sadiqabad',
  'Khanewal',
  'Hafizabad',
  'Kohat',
  'Jacobabad',
  'Shikarpur',
  'Muzaffargarh',
  'Khanpur',
  'Gojra',
  'Bahawalnagar',
  'Abbottabad',
  'Muridke',
  'Pakpattan',
  'Khuzdar',
  'Jaranwala',
  'Chishtian',
  'Daska',
  'Mandi Bahauddin',
  'Ahmadpur East',
  'Kamalia',
  'Tando Adam',
  'Khairpur',
  'Dera Ismail Khan',
  'Vehari',
  'Nowshera',
  'Dadu',
  'Wazirabad',
  'Khushab',
  'Charsada',
  'Swabi',
  'Chakwal',
  'Mianwali',
  'Tando Allahyar',
  'Kot Adu',
  'Farooka',
  'Chichawatni',
  'Mansehra',
  'Naran',
  'Hunza',
  'Gilgit',
  'Skardu',
];

export const countryData = [
  'Pakistan',
  'Australia',
  'India',
  'Canada',
  'New Zealand',
  'Kuwait',
  'Qatar',
  'Saudi Arabia',
  'South Africa',
  'USA',
  'UAE',
  'UK',
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Angola',
  'Anguilla',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (DRC)',
  'Congo',
  'Cook Island',
  'Costa Rica',
  'Cote',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji Islands',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao SAR',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Korea',
  'Norway',
  'Oman',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Samoa',
  'San Marino',
  'São Tomé and Príncipe',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'Spain',
  'Sri Lanka',
  'St Helena',
  'St Kitts and Nevis',
  'St Lucia',
  'St Pierre and Miquelon',
  'St Vincent and Grenadines',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Tobago',
  'Trinidad',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Virgin Islands',
  'Wallis and Futuna',
  'Yemen',
  'Yugoslavia',
  'Zambia',
  'Zimbabwe',
];

export const communityData = [
  'Punjabi',
  'Gujarati',
  'Urdu',
  'English',
  'Arabic',
  'Marwari',
  'Tamil',
  'Aka',
  'Awadhi',
  'Balochi',
  'Bhutia',
  'Brij',
  'Brahui',
  'Chinese',
  'Chattisgarhi',
  'Dogri',
  'French',
  'Garo',
  'Garhwali',
  'Hindko',
  'Kashmiri',
  'Nepali',
  'Pashto',
  'Persian',
  'Russian',
  'Sanskrit',
  'Seraiki',
  'Sindhi',
  'Sinhala',
  'Spanish',
  'Other',
];

export const religionData = [
  'Muslim',
  'Christian',
  'Hindu',
  'Sikh',
  'Buddhist',
  'No religion',
  'Other',
];

export const stateData = [
  'Azad Kashmir',
  'Balochistan',
  'Islamabad',
  'Sindh',
  'Punjab',
  'NorthWest Frontier',
  'Tribal Areas',
  'Northern Areas',
  'Other',
];

export const dietData = [
  'Veg',
  'Non-Veg',
  'Occasionally Non-Veg',
  'Eggetarian',
  'Jain',
  'Vegan',
];

export const heightData = [
  '134cm',
  '137cm',
  '139cm',
  '142cm',
  '144cm',
  '147cm',
  '149cm',
  '152cm',
  '154cm',
  '157cm',
  '160cm',
  '162cm',
  '165cm',
  '167cm',
  '170cm',
  '172cm',
  '175cm',
  '177cm',
  '180cm',
  '182cm',
  '185cm',
  '187cm',
  '190cm',
  '193cm',
  '195cm',
  '198cm',
  '200cm',
  '203cm',
  '205cm',
  '208cm',
  '210cm',
  '213cm',
];

export const qualificationData = [
  'B.E / B.Tech',
  'M.E / M.Tech',
  'M.S Engineering',
  'B.Eng (Hons)',
  'M.Eng (Hons)',
  'Engineering Diploma',
  'AE',
  'AET',

  'B.A',
  'B.Ed',
  'BJMC',
  'BFA',
  'B.Arch',
  'B.Des',
  'BMM',
  'MFA',
  'M.Ed',
  'M.A',
  'MSW',
  'MJMC',
  'M.Arch',
  'M.Des',
  'BA (Hons)',
  'B.Arch (Hons)',
  'DFA',
  'D.Ed',
  'D.Arch',
  'AA',
  'AFA',

  'B.Com',
  'CA/CPA',
  'CFA',
  'CS',
  'BSc/BFin',
  'M.Com',
  'MSc/ MFin / MS',
  'BCom (Hons)',
  'PGD Finance',

  'BCA',
  'B.IT',
  'BCS',
  'BA Computer Science',
  'MCA',
  'PGDCA',
  'It Diploma',
  'ADIT',

  'B.Sc',
  'M.Sc',
  'BSc (Hons)',
  'DipSc',
  'AS',
  'AAS',

  'MBBS',
  'BDS',
  'BPT',
  'BAMS',
  'BHMS',
  'B.Pharma',
  'BVSc',
  'BSN/BScN',
  'MDS',
  'MCh',
  'M.D',
  'M.S Medicine',
  'MPT',
  'DM',
  'M.Pharma',
  'MVSc',
  'MMed',
  'PGD Medicine',
  'ADN',

  'BBA',
  'BHM',
  'BBM',
  'MBA',
  'PGDM',
  'ABA',
  'ADBus',

  'BL / LLB',
  'ML / LLM',
  'LLB (Hons)',
  'ALA',

  'Ph.D',
  'M.Phil',

  'Bachelor',
  'Master',
  'Diploma',
  'Honours',
  'Doctorate',
  'Associate',

  'High School',
  'Less than High School',
];

export const asAData = [
  //
  'Banking Professional',
  'Chartered Accountant',
  'Company Secretary',
  'Finance Professional',
  'Investment Professional',
  'Accounting Professional (Others)',
  //
  'Admin Professional',
  'Human Resources Professional',
  //
  'Actor',
  'Advertising Professional',
  'Entertainment Professional',
  'Event Manager',
  'Journalist',
  'Media Professional',
  'Public Realtion Professional',
  //
  'Farming',
  'Horticulturist',
  'Agricultural Professional (others)',
  'AIRLINE & AVIATION',
  'Air Hostess/Flight Attendant',
  'Pilot / Co-Pilot',
  'Other Airline Professional',
  //
  'Architect',
  'Interior Design',
  'Landscape Architect',
  //
  'Animator',
  'Commercial Artist ',
  'Web / UX Designers',
  'Artist (Others)',
  //
  'Beautician',
  'Fashion Designer',
  'Hairstylist',
  'Jewellery Designer',
  'Designer (Others)',
  //
  'Customer Support / BPO / KPO Professional',
  //
  'IAS / IRS / IES / IFS',
  'Pakistan Police',
  'Law Enforcement',
  //
  'Airforce',
  'Army',
  'Navy',
  'Defense Services',
  //
  'Lecturer',
  'Professor',
  'Research Assistant',
  'Research Scholar',
  'Teacher',
  'Traning Professional (others)',
  //
  'Civil Engineer',
  'Electronics / Telecom Engineer',
  'Mechanical / Production Engineer',
  'Non IT Engineer',
  //
  'Chef / Sommelier / Food Critic',
  'Catering Professional',
  'Hotel & Hospitality Professionals',
  //
  'Software Developer / Programmer',
  'Software Consultant',
  'Hardware & Networking Professional',
  'Software Professional (Others)',
  //
  'Lawyer',
  'Legal Assistant',
  'Legal Professional (others)',
  //
  'Dentist',
  'Doctor',
  'Medical Transcriptionist',
  'Nurse',
  'Pharmacist',
  'Physician Assistant',
  'Physiotherapist / Occupational Therapist',
  'Psychologist',
  'Surgeon',
  'Veterinary Doctor',
  'Therapist (Others)',
  'Medical Healthcare Professional (Others)',
  //
  'Merchant Naval Officer',
  'Mariner',
  //
  'Marketing Professional',
  'Sales Professional',
  //
  'Biologist / Botanist',
  'Physicist',
  'Science Professional',
  //
  'CxO/ Chairman / Director / President',
  'VP / AVP / GM / DGM',
  'Sr.Manager / Manager',
  'Consultant / Supervisor / Team Leads',
  'Team Member / Staff',
  //
  'Agent / Broker / Trader / Contractor',
  'Business Owner / Entrepreneur',
  'Politician',
  'Social Worker / Volunteer / NGO',
  'Sportsman',
  'Travel & Transport Professional',
  'Writer ',
  //
  'Student',
  'Retired',
  'Not Working',
];

export const oftenPrayData = [
  'One time a day - 1',
  'Two times a day - 2',
  'Three times a day - 3',
  'Four times a day - 4 ',
  'Five times a day - 5',
  'Never - 0',
];

export const hobbiesData = [
  'Archery',
  'Blogging',
  'Calligraphy',
  'Cooking',
  'Dancing',
  'Sports',
  'Drawing',
  'Driving',
  'Fishing',
  'Gardening',
  'Hiking',
  'Homedecoration',
  'Investing',
  'Jewelrymaking',
  'Jogging',
  'Knitting',
  'Learningforeignlanguages',
  'Photography',
  'Poetry',
  'Puzzling',
  'Sewing',
  'Singing',
  'Hunting',
  'Swimming',
  'Makingfriends',
  'Shopping',
  'Eating',
  'Working',
  'Designing',
  'Exercising',
  'Internetsurfing',
  'Creative',
  'Games',
  'Camping',
  'Cycling',
  'Yoga',
];
